import Head from 'next/head';
import styles from '../styles/Home.module.css';
import MuiNextLink from '@components/core-components/MuiNextLink';
import { Container, Stack } from '@mui/material';
import GetStarted from '@components/GetStarted';
import MintNFT from '@components/web3/mint-nft';

export default function Home() {
  return (
    <div>
      <Head id="home">
        
        <title>web3-react with nft merkle tree minting scaffold</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
        <img src="\lov1.png" alt="Avatar" width='100%'></img>
        </h1>
        <GetStarted />
        <MintNFT />
        
      </main>
    </div>
  )
}
